eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  secret:
    audiences:
      - UserService
      - PostService
      - FeedService
      - UserAchievementsService
      - CommentModeratorService
    token:
        issuer: AuthService
    commentModeratorService:
      audience: CommentModeratorService
      key: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IkNvbW1lbnRNb2RlcmF0b3JTZXJ2aWNlIiwic3ViIjoiY29tbWVudC1tb2RlcmF0b3Itc2VydmljZSIsImV4cCI6MTY1NjYwMzEzOSwiY2FuLXJlYWQiOnRydWUsImNhbi13cml0ZSI6dHJ1ZSwiY2FuLWVkaXQiOnRydWV9.3N2EbIeXuZywFtQ06CuAVksZ2kaPZSrgXzTcQeACsJqOPNfDkzVsxRM4WoPEQPIWqGfv9mvxVQ7-BJiIb5etmQ
    feedService:
      audience: FeedService
      key: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IkZlZWRTZXJ2aWNlIiwic3ViIjoiZmVlZC1zZXJ2aWNlIiwiZXhwIjoxNjU2NjAzMTM5LCJjYW4tcmVhZCI6dHJ1ZSwiY2FuLXdyaXRlIjp0cnVlLCJjYW4tZWRpdCI6dHJ1ZX0.re8BrcRoBL12cWbEWVM2z--RflR3lPOwFD46dPtSdj8lpYjzTYWzQlnzVS-T7l_vJFzvcN7ahh0d_CwxAl_-tA
    postService:
      audience: PostService
      key: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IlBvc3RTZXJ2aWNlIiwic3ViIjoicG9zdC1zZXJ2aWNlIiwiZXhwIjoxNjU2NjAzMTM5LCJjYW4tcmVhZCI6dHJ1ZSwiY2FuLXdyaXRlIjp0cnVlLCJjYW4tZWRpdCI6dHJ1ZX0.UPoHqI2DF9CdkHwyeXbGRXHlphnrXH2jUluHC1doMbo_6fJlRn7mtzy1RxdwSRwnDYqg23AJ1XncQjNhTTQyrw
    userAchievementsService:
      audience: UserAchievementsService
      key: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IlVzZXJBY2hpZXZlbWVudHNTZXJ2aWNlIiwic3ViIjoidXNlci1hY2hpZXZlbWVudHMtc2VydmljZSIsImV4cCI6MTY1NjYwMzEzOSwiY2FuLXJlYWQiOnRydWUsImNhbi13cml0ZSI6dHJ1ZSwiY2FuLWVkaXQiOnRydWV9.n04WIYBUYZ5OH7NTCdp8CJJWwwXayWbh1pnzMIHgyThpu2sAgggxsrjXtdv3LV7BtP_ZYFPpy9v8Y6Ei1fcQ5g
    userService:
      audience: UserService
      key: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IlVzZXJTZXJ2aWNlIiwic3ViIjoidXNlci1zZXJ2aWNlIiwiZXhwIjoxNjU2NjAzMTM5LCJjYW4tcmVhZCI6dHJ1ZSwiY2FuLXdyaXRlIjp0cnVlLCJjYW4tZWRpdCI6dHJ1ZX0.0p9I6mypPIhFVB9NMrqOgN9ZxYO_fYep5LUI2KqFMe24CNk5diOtpb10cvqqY5oyQb_6wqCR4WYwUzOLsLRYvQ
